INVOICE_STATUS_DRAFT = "draft"
INVOICE_STATUS_SENT = "sent"
INVOICE_STATUS_VIEWED = "viewed"
INVOICE_STATUS_PARTIALLY_PAID = "partially_paid"
INVOICE_STATUS_PAID = "paid"
INVOICE_STATUS_OVERDUE = "overdue"

INVOICE_STATUSES = (
    INVOICE_STATUS_DRAFT,
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VIEWED,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_OVERDUE,
)

OUTSTANDING_INVOICE_STATUSES = (
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VIEWED,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_OVERDUE,
)

FOLLOW_UP_DAYS = (3, 7, 14)
INITIAL_FOLLOW_UP_DAY = 0
DEFAULT_CURRENCY = "usd"
