INVOICE_STATUS_DRAFT = "draft"
INVOICE_STATUS_SENT = "sent"
INVOICE_STATUS_VIEWED = "viewed"
INVOICE_STATUS_PARTIALLY_PAID = "partially_paid"
INVOICE_STATUS_PAID = "paid"
INVOICE_STATUS_OVERDUE = "overdue"

INVOICE_STATUSES = (
    INVOICE_STATUS_DRAFT,
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VIEWED,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_OVERDUE,
)

OUTSTANDING_INVOICE_STATUSES = (
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_VIEWED,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_OVERDUE,
)

FOLLOW_UP_DAYS = (3, 7, 14)
INITIAL_FOLLOW_UP_DAY = 0
DEFAULT_CURRENCY = "usd"

COLLECTION_CASE_STATUS_NEEDS_ANALYSIS = "needs_analysis"
COLLECTION_CASE_STATUS_ACTION_READY = "action_ready"
COLLECTION_CASE_STATUS_AWAITING_CLIENT = "awaiting_client"
COLLECTION_CASE_STATUS_PROMISE_TO_PAY = "promise_to_pay"
COLLECTION_CASE_STATUS_PAYMENT_PLAN = "payment_plan"
COLLECTION_CASE_STATUS_NEEDS_HUMAN_REVIEW = "needs_human_review"
COLLECTION_CASE_STATUS_RESOLVED = "resolved"

COLLECTION_CASE_STATUSES = (
    COLLECTION_CASE_STATUS_NEEDS_ANALYSIS,
    COLLECTION_CASE_STATUS_ACTION_READY,
    COLLECTION_CASE_STATUS_AWAITING_CLIENT,
    COLLECTION_CASE_STATUS_PROMISE_TO_PAY,
    COLLECTION_CASE_STATUS_PAYMENT_PLAN,
    COLLECTION_CASE_STATUS_NEEDS_HUMAN_REVIEW,
    COLLECTION_CASE_STATUS_RESOLVED,
)

COLLECTION_RISK_LEVEL_HIGH = "high"
COLLECTION_RISK_LEVEL_MEDIUM = "medium"
COLLECTION_RISK_LEVEL_LOW = "low"

COLLECTION_RISK_LEVELS = (
    COLLECTION_RISK_LEVEL_HIGH,
    COLLECTION_RISK_LEVEL_MEDIUM,
    COLLECTION_RISK_LEVEL_LOW,
)

COLLECTION_REPLY_CLASSIFICATION_PROMISE_TO_PAY = "promise_to_pay"
COLLECTION_REPLY_CLASSIFICATION_PAYMENT_PLAN_REQUEST = "payment_plan_request"
COLLECTION_REPLY_CLASSIFICATION_PAID_ELSEWHERE = "paid_elsewhere"
COLLECTION_REPLY_CLASSIFICATION_DISPUTE = "dispute"
COLLECTION_REPLY_CLASSIFICATION_QUESTION = "question"
COLLECTION_REPLY_CLASSIFICATION_UNKNOWN = "unknown"

COLLECTION_REPLY_CLASSIFICATIONS = (
    COLLECTION_REPLY_CLASSIFICATION_PROMISE_TO_PAY,
    COLLECTION_REPLY_CLASSIFICATION_PAYMENT_PLAN_REQUEST,
    COLLECTION_REPLY_CLASSIFICATION_PAID_ELSEWHERE,
    COLLECTION_REPLY_CLASSIFICATION_DISPUTE,
    COLLECTION_REPLY_CLASSIFICATION_QUESTION,
    COLLECTION_REPLY_CLASSIFICATION_UNKNOWN,
)

COLLECTION_COMMITMENT_TYPE_PROMISE_TO_PAY = "promise_to_pay"
COLLECTION_COMMITMENT_TYPE_PAYMENT_PLAN_INSTALLMENT = "payment_plan_installment"

COLLECTION_COMMITMENT_TYPES = (
    COLLECTION_COMMITMENT_TYPE_PROMISE_TO_PAY,
    COLLECTION_COMMITMENT_TYPE_PAYMENT_PLAN_INSTALLMENT,
)

COLLECTION_COMMITMENT_STATUS_ACTIVE = "active"
COLLECTION_COMMITMENT_STATUS_SUPERSEDED = "superseded"
